# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "api/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "01:00"
      timezone: "Europe/Rome"
    assignees:
      - "zerai"
    labels:
      - "PHP dependency"
    groups:
      symfony_dev:
        applies-to: "version-updates"
        dependency-type: "development"
        patterns:
          - "symfony/stopwatch"
          - "symfony/browser-kit"
          - "symfony/debug-bundle"
          - "symfony/css-selector"
          - "symfony/phpunit-bridge"
          - "symfony/web-profiler-bundle"
        update-types:
          - "patch"
      symfony_prod:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "symfony/*"
        update-types:
          - "patch"
      doctrine:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "doctrine/*"
        update-types:
          - "patch"
      ecotone:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "ecotone/*"
        update-types:
          - "minor"
          - "patch"
      pagerfanta:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "babdev/pagerfanta-bundle"
          - "pagerfanta/*"
        update-types:
          - "minor"
          - "patch"
      twig-extra:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "twig/extra-bundle"
          - "twig/*-extra"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "doctrine/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor" ]


  ########################################################################################################################
  #
  #   Github Actions dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "api/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    labels:
      - "GHA dependency"