
services:
###> doctrine/doctrine-bundle ###
  database:
    volumes:
      - ./sys/docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: app_test
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###



  ######################################################################################################################
  #
  #   Messaging & queue - RabbitMq
  #
  ######################################################################################################################
  mbroker:
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
      # HTTP
      - target: 15672
        published: ${RABBITMQ_HTTP_PORT:-15672}
        protocol: tcp
