api_platform:
    title: S-eco API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    mapping:
        # The list of paths with files or directories where the bundle will look for additional resource files.
        paths: [ '%kernel.project_dir%/context/ingesting/src/Infrastructure/ApiPlatform/Resource/' ]
    keep_legacy_inflector: false
    use_symfony_listeners: true
